server:
  port: 8080
spring:
  application:
    name: Backendserice
  profiles:
    active: ${STAGE:local}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /
flyway:
  baseline-on-migrate:  true