server:
  port: 8080
spring:
  application:
    name: Backendserice
  profiles:
    active: ${STAGE:local}
  jpa:
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /
  rabbitmq:
        host: ${rabbitmq:localhost}
        username: guest
        password: guest
flyway:
  baseline-on-migrate:  true
paymentservice:
  url: ${PAYMENTSERVICE:http://localhost:8081}