spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=PostgreSQL
  datasource:
    driver-class-name:  org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webshop
    username: postgres
    password: Post$Gres
    schema: webshop
  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  data:
    rest:
      base-path: /
flyway:
  baseline-on-migrate:  true