server:
  port: 8084
spring:
  application:
    name: Printservice
  profiles:
    active: ${STAGE:local}
  rabbitmq:
        host: ${rabbitmq:localhost}
        username: guest
        password: guest