server:
  port: 8083
spring:
  application:
    name: Emailservice
  profiles:
    active: ${STAGE:local}
  rabbitmq:
          host: ${rabbitmq:localhost}
          username: guest
          password: guest