server:
  port: 8082
spring:
  application:
    name: Frontendservice
  profiles:
    active: ${STAGE:local}
  rabbitmq:
        host: ${rabbitmq:localhost}
        username: guest
        password: guest
backendservice:
  url: http://localhost:8080